import { motion, useReducedMotion } from 'framer-motion'
import { useState } from 'react'
import { deKingQuiz } from '../data/quiz'
import { isQuizComplete, scoreQuizAnswers, type QuizAnswer } from '../utils/quiz'
export function DeKingQuiz({ onAdvance, onBack }: { onAdvance: () => void; onBack: () => void }) {
  const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<QuizAnswer[]>(() => deKingQuiz.map(() => null)); const reduceMotion = useReducedMotion(); const question = deKingQuiz[index]; const complete = isQuizComplete(answers); const score = scoreQuizAnswers(answers, deKingQuiz.map((item) => item.answer))
  const choose = (answer: number) => { const next = [...answers]; next[index] = answer; setAnswers(next) }
  if (complete) return <main className="scene chapter-scene quiz-scene"><p className="eyebrow">Quiz complete</p><motion.section className="quiz-result" initial={reduceMotion ? false : { opacity: 0, scale: .95 }} animate={{ opacity: 1, scale: 1 }}><span>{score} / {deKingQuiz.length}</span><h1>Whatever your score says,<br /><em>you still passed the only test that matters.</em></h1><p>You have my heart.</p><h2>WE WIN.</h2><div className="chapter-actions"><button className="text-button compact" onClick={() => { setAnswers(deKingQuiz.map(() => null)); setIndex(0) }}>Play again</button><button className="primary-button" onClick={onAdvance}>Continue</button></div></motion.section></main>
  return <main className="scene chapter-scene quiz-scene"><p className="eyebrow">Chapter 09 · How well do you know De King?</p><section className="quiz-card"><div className="quiz-progress"><span>Question {index + 1}</span><b>{index + 1} / {deKingQuiz.length}</b></div><i><b style={{ width: `${((index + 1) / deKingQuiz.length) * 100}%` }} /></i><motion.div key={question.id} initial={reduceMotion ? false : { opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }}><h1>{question.prompt}</h1><div className="quiz-options">{question.options.map((option, optionIndex) => <button className={answers[index] === optionIndex ? 'selected' : ''} key={option} onClick={() => choose(optionIndex)}>{option}</button>)}</div></motion.div><div className="chapter-actions"><button className="text-button compact" onClick={index === 0 ? onBack : () => setIndex((value) => value - 1)}>{index === 0 ? 'Back' : 'Previous'}</button><button className="primary-button" disabled={answers[index] === null} onClick={() => index === deKingQuiz.length - 1 ? setIndex(index) : setIndex((value) => value + 1)}>{index === deKingQuiz.length - 1 ? 'See my result' : 'Next question'}</button></div></section></main>
}