import { motion, useReducedMotion } from 'framer-motion'
import { BookOpen, CalendarHeart, Clock3, Music2, ScrollText, Sparkles, Vault } from 'lucide-react'
import { useEffect, useState } from 'react'
import { birthday } from '../data/birthday'
import { cornerMessages } from '../data/messages'
import { secretById } from '../data/secrets'
import { useLocalStorage } from '../hooks/useLocalStorage'
import { countdownTo, isBirthdayToday, nextBirthdayOccurrence } from '../utils/countdown'
import { addDiscovery, discoveryCount, hasDiscovery } from '../utils/discoveries'
import type { ChapterId } from '../utils/chapterFlow'
const items: { title: string; chapter: ChapterId; icon: typeof BookOpen }[] = [
  { title: 'Our Story', chapter: 'ourStory', icon: BookOpen }, { title: 'Memory Lane', chapter: 'memoryLane', icon: Sparkles }, { title: 'The Music Room', chapter: 'musicRoom', icon: Music2 }, { title: 'The Letter', chapter: 'letter', icon: ScrollText }, { title: 'Our Future', chapter: 'future', icon: CalendarHeart }, { title: 'My Promise', chapter: 'promise', icon: Clock3 }, { title: 'Birthday Vault', chapter: 'birthdayVault', icon: Vault },
]
function useNow() { const [now, setNow] = useState(() => new Date()); useEffect(() => { const id = window.setInterval(() => setNow(new Date()), 1000); return () => clearInterval(id) }, []); return now }
export function LittleCorner({ onNavigate, onRelive }: { onAdvance: () => void; onBack: () => void; onNavigate: (chapter: ChapterId) => void; onRelive: () => void }) {
  const [entered, setEntered] = useState(false); const [discoveries, setDiscoveries] = useLocalStorage<string[]>('adebimpe.discoveries', []); const [notice, setNotice] = useState<string | null>(null); const now = useNow(); const reduceMotion = useReducedMotion(); const birthdayToday = isBirthdayToday(birthday.date, now); const count = countdownTo(nextBirthdayOccurrence(birthday.date, now), now); const message = cornerMessages[now.getDate() % cornerMessages.length]; const welcome = birthdayToday ? 'Happy Birthday,' : 'Welcome back,'
  const discover = (id: string) => { const secret = secretById(id); if (secret && !hasDiscovery(discoveries, id)) { setDiscoveries((saved) => addDiscovery(saved, id)); setNotice(secret.message) } }
  return <main className="scene chapter-scene corner-scene"><p className="eyebrow">Adebimpe’s Little Corner</p><h1>{welcome}<br /><em>Adebimpe Omo Oba.</em></h1><p className="corner-subtitle">This little corner is still yours.</p>{!entered ? <motion.section className="corner-entry" initial={reduceMotion ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><p>{discoveries.length ? 'You found your way back. There may still be little things waiting.' : message}</p><button className="primary-button" onClick={() => setEntered(true)}>Enter my corner</button><button className="text-button compact" onClick={onRelive}>Relive the birthday</button></motion.section> : <><motion.section className="countdown-card" initial={reduceMotion ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><button className="birthday-discovery" onClick={() => birthdayToday && discover('birthday-whisper')} aria-label={birthdayToday ? 'Today is your day. Tap for a small birthday discovery.' : 'Next birthday countdown'}><p className="eyebrow">{birthdayToday ? 'Today is your day' : 'Next birthday'}</p>{birthdayToday ? <h2>TODAY IS YOUR DAY</h2> : <div className="countdown-values">{Object.entries(count).map(([label, value]) => <div key={label}><strong>{String(value).padStart(2, '0')}</strong><small>{label}</small></div>)}</div>}</button></motion.section><p className="corner-message">{message}</p><div className="corner-grid">{items.map((item) => { const Icon = item.icon; return <button key={item.chapter} onClick={() => onNavigate(item.chapter)}><Icon /><span>{item.title}</span><small>Open</small></button> })}</div><p className="discovery-summary">{discoveryCount(discoveries)} little {discoveryCount(discoveries) === 1 ? 'thing' : 'things'} discovered</p>{notice && <motion.p className="discovery-notice" role="status" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>{notice}</motion.p>}<button className="de-king-signature" onClick={() => discover('de-king-signature')}>From De King</button><div className="chapter-actions"><button className="text-button compact" onClick={onRelive}>Relive the birthday</button></div></>}</main>
}