import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { Image, X } from 'lucide-react'
import { useState } from 'react'
import { memories, type Memory } from '../data/memories'

export function MemoryLane({ onAdvance, onBack }: { onAdvance: () => void; onBack: () => void }) {
  const [selected, setSelected] = useState<Memory | null>(null); const [unavailablePhotos, setUnavailablePhotos] = useState<ReadonlySet<string>>(new Set()); const [fullscreenPhoto, setFullscreenPhoto] = useState<string | null>(null); const reduceMotion = useReducedMotion()
  const openMemory = (memory: Memory) => { setUnavailablePhotos((current) => { const next = new Set(current); next.delete(memory.id); return next }); setSelected(memory) }
  const photoSrc = selected?.photoSrc
  const photoIsAvailable = selected && photoSrc && !unavailablePhotos.has(selected.id)
  return <main className="scene chapter-scene memory-scene"><p className="eyebrow">Chapter 06 · Memory Lane</p><h1>A little archive of<br /><em>what became ours.</em></h1><p className="chapter-lead">Tap a memory to let it open.</p><div className="memory-rail">{memories.map((memory, index) => <button type="button" className="memory-card" onClick={() => openMemory(memory)} key={memory.id}><span>{String(index + 1).padStart(2, '0')}</span><strong>{memory.title}</strong><p>{memory.summary}</p><small>Open memory</small></button>)}</div><div className="chapter-actions"><button type="button" className="text-button compact" onClick={onBack}>Back</button><button type="button" className="primary-button" onClick={onAdvance}>Keep going</button></div><AnimatePresence>{selected && <motion.div className="card-dialog-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelected(null)}><motion.section role="dialog" aria-modal="true" aria-labelledby="memory-title" className="card-dialog memory-dialog" initial={reduceMotion ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} onClick={(event) => event.stopPropagation()}><button type="button" autoFocus className="dialog-close" onClick={() => setSelected(null)} aria-label="Close memory"><X /></button>{photoIsAvailable ? <img className="memory-photo" src={photoSrc} alt={`Memory: ${selected.title}`} onClick={() => setFullscreenPhoto(photoSrc)} onError={() => setUnavailablePhotos((current) => new Set(current).add(selected.id))} style={{ cursor: 'pointer' }} /> : <div className="photo-placeholder"><Image size={22} /><span>Photo unavailable: <strong>{selected.photoFilename}</strong></span></div>}<p className="eyebrow">Memory archive</p><h2 id="memory-title">{selected.title}</h2><p>{selected.detail ?? selected.summary}</p><button type="button" className="text-button compact" onClick={() => setSelected(null)}>Close</button></motion.section></motion.div>}</AnimatePresence><AnimatePresence>{fullscreenPhoto && <motion.div className="fullscreen-photo-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setFullscreenPhoto(null)}><motion.div className="fullscreen-photo-container" initial={reduceMotion ? false : { scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }} onClick={(event) => event.stopPropagation()}><button type="button" className="fullscreen-close" onClick={() => setFullscreenPhoto(null)} aria-label="Close full-screen image"><X size={32} /></button><img className="fullscreen-photo" src={fullscreenPhoto} alt="Full-screen memory photo" /></motion.div></motion.div>}</AnimatePresence></main>
}
